### PR TITLE
Fix casing of JSON format strings

### PR DESCRIPTION
**Pull request by rossf7**

### CODE REVIEW

**Comment by rossf7** [comment]
@xh3b4sd I've fixed the casing for Ingress Controller but the same problem is in several other places. Shall I fix these too?

https://github.com/giantswarm/clustertpr/blob/master/kubernetes/api/api.go

**Review by xh3b4sd — APPROVED** [review]
<3

**Comment by xh3b4sd** [comment]
We can also fix other places where we got it wrong.

**Comment by rossf7** [comment]
@xh3b4sd PR is updated PTAL

**Review by xh3b4sd — APPROVED** [review]
Thanks for taking care.

**Pull request merged**
